homepage: { module: default, action: index, url: / }

login: { module: default, action: login, url: /login, suffix: html }

logout: { module: default, action: logout, url: /logout }

header: { module: header, action: index, url: /header }
