homepage    : 'default index'
secure      : 'default notallowed'

# module: module
module_add  : 'module create'
module_del  : 'module delete'
module_ren  : 'module rename'

# module: action
action_add  : 'action create'
action_del  : 'action delete'
action_ren  : 'action rename'

# module: component
comp_add  : 'component create'
comp_del  : 'component delete'
comp_ren  : 'component rename'

# module: action-template
act_tmplt_add   : 'template act_create'
act_tmplt_del   : 'template act_delete'
act_tmplt_ren   : 'template act_rename'

# module: component-template
comp_tmplt_add   : 'template comp_create'
comp_tmplt_del   : 'template comp_delete'
comp_tmplt_ren   : 'template comp_rename'

